/* tslint:disable */
export const fileNames = {
	'angular-cli.json': '_file_angular',
	'bower.json': '_file_bower',
	license: '_file_license',
	LICENSE: '_file_license',
	'license.txt': '_file_license',
	'license.md': '_file_license',
	'LICENSE.txt': '_file_license',
	'LICENSE.md': '_file_license',
	copying: '_file_license',
	COPYING: '_file_license',
	'copying.txt': '_file_license',
	'copying.md': '_file_license',
	'COPYING.txt': '_file_license',
	'COPYING.md': '_file_license',
	dockerfile: '_file_docker',
	notice: '_file_license',
	NOTICE: '_file_license',
	'notice.txt': '_file_license',
	'notice.md': '_file_license',
	'NOTICE.txt': '_file_license',
	'NOTICE.md': '_file_license',
	'docker-compose': '_file_docker',
	'docker-compose.yml': '_file_docker',
	'docker-compose.yaml': '_file_docker',
	'docker-compose.ci-build': '_file_docker',
	'docker-compose.override': '_file_docker',
	'docker-compose.vs.debug': '_file_docker',
	'docker-compose.vs.release': '_file_docker',
	'docker-cloud': '_file_docker',
	emakefile: '_file_erlang',
	'go.sum': '_file_go',
	'go.mod': '_file_go',
	'gruntfile.js': '_file_grunt',
	'gruntfile.coffee': '_file_grunt',
	'gruntfile.ts': '_file_grunt',
	'gruntfile.babel.js': '_file_grunt',
	'gruntfile.babel.coffee': '_file_grunt',
	'gruntfile.babel.ts': '_file_grunt',
	'gulpfile.js': '_file_gulp',
	'gulpfile.coffee': '_file_gulp',
	'gulpfile.ts': '_file_gulp',
	'gulpfile.babel.js': '_file_gulp',
	'gulpfile.babel.coffee': '_file_gulp',
	'gulpfile.babel.ts': '_file_gulp',
	'package.json': '_file_npm',
	'package-lock.json': '_file_package-lock',
	'yarn.lock': '_file_yarn-lock',
	'yarn-error.log': '_file_yarn',
	makefile: '_file_make',
	'cmakelists.txt': '_file_make',
	'postcss.config.js': '_file_postcss',
	'postcss.config.ts': '_file_postcss',
	'postcss.config.mjs': '_file_postcss',
	'postcss.config.cjs': '_file_postcss',
	'postcss.config.mts': '_file_postcss',
	'postcss.config.cts': '_file_postcss',
	CODEOWNERS: '_file_github',
	'tsconfig.json': '_file_tsconfig',
	'tsconfig.jsonc': '_file_tsconfig',
	'tsconfig.paths.json': '_file_tsconfig',
	'tsconfig.paths.jsonc': '_file_tsconfig',
	'tsconfig.base.json': '_file_tsconfig',
	'tsconfig.base.jsonc': '_file_tsconfig',
	'tsconfig.root.json': '_file_tsconfig',
	'tsconfig.root.jsonc': '_file_tsconfig',
	'tsconfig.references.json': '_file_tsconfig',
	'tsconfig.references.jsonc': '_file_tsconfig',
	'tsconfig.dev.json': '_file_tsconfig',
	'tsconfig.dev.jsonc': '_file_tsconfig',
	'tsconfig.prod.json': '_file_tsconfig',
	'tsconfig.prod.jsonc': '_file_tsconfig',
	'tsconfig.test.json': '_file_tsconfig',
	'tsconfig.test.jsonc': '_file_tsconfig',
	'tsconfig.build.json': '_file_tsconfig',
	'tsconfig.build.jsonc': '_file_tsconfig',
	'tsconfig.src.json': '_file_tsconfig',
	'tsconfig.src.jsonc': '_file_tsconfig',
	'tsconfig.app.json': '_file_tsconfig',
	'tsconfig.app.jsonc': '_file_tsconfig',
	'tsconfig.node.json': '_file_tsconfig',
	'tsconfig.node.jsonc': '_file_tsconfig',
	'typescript.yml': '_file_tsconfig',
	'typescript.yaml': '_file_tsconfig',
	'tslint.json': '_file_tsconfig',
	'composer.lock': '_file_json',
	'stylelint.config.js': '_file_stylelint',
	'stylelint.config.ts': '_file_stylelint',
	'stylelint.config.json': '_file_stylelint',
	'stylelint.config.yml': '_file_stylelint',
	'stylelint.config.yaml': '_file_stylelint',
	'ionic.config.json': '_file_ionic',
	'.io-config.json': '_file_ionic',
	'babelrc.js': '_file_babel',
	'babelrc.json': '_file_babel',
	'babel.config.js': '_file_babel',
	'webpack.base.conf.js': '_file_webpack',
	'webpack.base.conf.ts': '_file_webpack',
	'webpack.common.js': '_file_webpack',
	'webpack.common.ts': '_file_webpack',
	'webpack.config.js': '_file_webpack',
	'webpack.config.ts': '_file_webpack',
	'webpack.config.base.js': '_file_webpack',
	'webpack.config.base.ts': '_file_webpack',
	'webpack.config.common.js': '_file_webpack',
	'webpack.config.common.ts': '_file_webpack',
	'webpack.config.dev.js': '_file_webpack',
	'webpack.config.dev.ts': '_file_webpack',
	'webpack.config.development.js': '_file_webpack',
	'webpack.config.development.ts': '_file_webpack',
	'webpack.config.staging.js': '_file_webpack',
	'webpack.config.staging.ts': '_file_webpack',
	'webpack.config.test.js': '_file_webpack',
	'webpack.config.test.ts': '_file_webpack',
	'webpack.config.prod.js': '_file_webpack',
	'webpack.config.prod.ts': '_file_webpack',
	'webpack.config.production.js': '_file_webpack',
	'webpack.config.production.ts': '_file_webpack',
	'webpack.config.babel.js': '_file_webpack',
	'webpack.config.babel.ts': '_file_webpack',
	'webpack.config.base.babel.js': '_file_webpack',
	'webpack.config.base.babel.ts': '_file_webpack',
	'webpack.config.common.babel.js': '_file_webpack',
	'webpack.config.common.babel.ts': '_file_webpack',
	'webpack.config.dev.babel.js': '_file_webpack',
	'webpack.config.dev.babel.ts': '_file_webpack',
	'webpack.config.development.babel.js': '_file_webpack',
	'webpack.config.development.babel.ts': '_file_webpack',
	'webpack.config.staging.babel.js': '_file_webpack',
	'webpack.config.staging.babel.ts': '_file_webpack',
	'webpack.config.test.babel.js': '_file_webpack',
	'webpack.config.test.babel.ts': '_file_webpack',
	'webpack.config.prod.babel.js': '_file_webpack',
	'webpack.config.prod.babel.ts': '_file_webpack',
	'webpack.config.production.babel.js': '_file_webpack',
	'webpack.config.production.babel.ts': '_file_webpack',
	'webpack.dev.js': '_file_webpack',
	'webpack.dev.ts': '_file_webpack',
	'webpack.dev.conf.js': '_file_webpack',
	'webpack.dev.conf.ts': '_file_webpack',
	'webpack.prod.js': '_file_webpack',
	'webpack.prod.ts': '_file_webpack',
	'webpack.prod.conf.js': '_file_webpack',
	'webpack.prod.conf.ts': '_file_webpack',
	'webpack.mix.js': '_file_webpack',
	'webpack.mix.ts': '_file_webpack',
	'webpack.test.conf.js': '_file_webpack',
	'webpack.test.conf.ts': '_file_webpack',
	'rollup.config.js': '_file_rollup',
	'rollup-config.ts': 'file_rollup',
	'rollup.config.common.js': 'file_rollup',
	'rollup.config.common.ts': 'file_rollup',
	'rollup.config.base.js': 'file_rollup',
	'rollup.config.base.ts': 'file_rollup',
	'rollup.config.prod.js': 'file_rollup',
	'rollup.config.prod.ts': 'file_rollup',
	'rollup.config.dev.js': 'file_rollup',
	'rollup.config.dev.ts': 'file_rollup',
	'rollup.config.prod.vendor.js': 'file_rollup',
	'rollup.config.prod.vendor.ts': 'file_rollup',
	'jest.config.js': '_file_jest',
	'jest.json': '_file_jest',
	'jest.config.json': '_file_jest',
	'jest.config.ts': '_file_jest',
	'jest.setup.js': '_file_jest',
	'jest.setup.ts': '_file_jest',
	'jest.teardown.js': '_file_jest',
	'contributing.md': '_file_contributing',
	'code_of_conduct.md': '_file_conduct',
	'code-of-conduct.md': '_file_conduct',
	'gatsby-config.js': '_file_gatsby',
	'gatsby-config.ts': '_file_gatsby',
	'gatsby-node.js': '_file_gatsby',
	'gatsby-node.ts': '_file_gatsby',
	'gatsby-browser.js': '_file_gatsby',
	'gatsby-browser.ts': '_file_gatsby',
	'gatsby-ssr.js': '_file_gatsby',
	'gatsby-ssr.ts': '_file_gatsby',
	'readme.md': '_file_readme',
	'README.md': '_file_readme',
	'README': '_file_readme',
	changelog: '_file_changelog',
	'changelog.md': '_file_changelog',
	favicon: '_file_favicon',
	'prettier.config.js': '_file_prettier',
	'mix.lock': '_file_elixir-lock',
	'now.json': '_file_now',
	browserslistrc: '_file_browserlist',
	'nuxt.config.js': '_file_nuxtconfig',
	'vue.config.js': '_file_vue',
	"build.zig": '_file_zig',
	"build.zig.zon": '_file_zig',
	// added by @colin
	'cargo.toml': '_file_cargo',
	'cargo.lock': '_file_cargo-lock',
	'pnpm-lock.yaml': '_file_pnpm',
	'pnpm-lock.yml': '_file_pnpm',
	'pnpm-workspace.yaml': '_file_pnpm',
	'pnpm-workspace.yml': '_file_pnpm',
	'eslint.config.js': '_file_eslint',
	'eslint.config.mjs': '_file_eslint',
	'eslint.config.cjs': '_file_eslint',
	'eslint.config.ts': '_file_eslint',
	'eslint.config.mts': '_file_eslint',
	'eslint.config.cts': '_file_eslint',
	'biome.json': '_file_biome',
	'biome.jsonc': '_file_biome',
	'tailwind.config.js': '_file_tailwindcss',
	'tailwind.config.ts': '_file_tailwindcss',
	'drizzle.config.ts': '_file_drizzle',
	'drizzle.config.js': '_file_drizzle',
	'drizzle-dev.config.ts': '_file_drizzle',
	'drizzle-dev.config.js': '_file_drizzle',
	'drizzle-prod.config.ts': '_file_drizzle',
	'drizzle-prod.config.js': '_file_drizzle',
	'drizzle-staging.config.ts': '_file_drizzle',
	'drizzle-staging.config.js': '_file_drizzle',
	'drizzle-test.config.ts': '_file_drizzle',
	'drizzle-test.config.js': '_file_drizzle',
	'next.config.ts': '_file_next',
	'next.config.js': '_file_next',
	'next.config.mjs': '_file_next',
	'next-env.d.ts': '_file_next-faded',
	'svelte.config.js': '_file_svelte',
	'vite.config.ts': '_file_vite',
	'vite.config.js': '_file_vite',
	'sst.config.ts': '_file_sst',
	'sst.config.js': '_file_sst',
	'sst-env.d.ts': '_file_sst-skeleton',
	'wrangler.toml': '_file_wrangler',
	'wrangler.json': '_file_wrangler',
	'wrangler.jsonc': '_file_wrangler',
	'bunfig.toml': '_file_bun',
	'bun.lockb': '_file_bun-skeleton',
	'bun.lock': '_file_bun',
	'bun.d.ts': '_file_bun-skeleton',
	'turbo.json': '_file_turborepo',
	'turbo.jsonc': '_file_turborepo',
	'wxt.config.ts': '_file_wxt',
	'wxt.config.js': '_file_wxt',
	'wxt.config.mjs': '_file_wxt',
	'devbox.json': '_file_nix',
	'flake.lock': '_file_nix-lock',
	'devbox.lock': '_file_nix-lock',
	'devenv.lock': '_file_nix-lock',
	'vitest.config.ts': '_file_vitest',
	'vitest.config.js': '_file_vitest',
	'vitest.config.mjs': '_file_vitest',
	'vitest.config.cjs': '_file_vitest',
	'vitest.config.mts': '_file_vitest',
	'vitest.config.cts': '_file_vitest',
	'vitest.shared.ts': '_file_vitest',
	'vitest.shared.js': '_file_vitest',
	'vitest.shared.mjs': '_file_vitest',
	'vitest.shared.cjs': '_file_vitest',
	'vitest.shared.mts': '_file_vitest',
	'vitest.shared.cts': '_file_vitest',
	'vitest.workspace.ts': '_file_vitest',
	'vitest.workspace.js': '_file_vitest',
	'vitest.workspace.mjs': '_file_vitest',
	'vitest.workspace.cjs': '_file_vitest',
	'vitest.workspace.mts': '_file_vitest',
	'vitest.workspace.cts': '_file_vitest',
  '.oxlintrc.json': '_file_oxc',
	'.oxlintrc.jsonc': '_file_oxc',
	'.codespellrc': '_file_settings',
	'.codespellignore': '_file_settings',
	// jenkinsfile: '_file_jenkins',
	// 'gatsby.config.js': '_file_gatsby',
	// 'firebase.json': '_file_firebase',
	// '.firebaserc': '_file_firebase',

	// 'gradle.properties': '_file_gradle',
	// gradlew: '_file_gradle',
	// 'androidmanifest.xml': '_file_android',
	// 'gradle-wrapper.properties': '_file_gradle',
	// procfile: '_file_procfile',
	// dockerfile: '_file_docker',
	// 'babel.config.js': '_file_babel',
	// '.babelrc': '_file_babel',
	// '.babelrc.js': '_file_babel',
	// '.babelrc.json': '_file_babel',
	// '.htaccess': '_file_xml',
	// '.gitignore': '_file_git',
	// '.gitconfig': '_file_git',
	// '.gitattributes': '_file_git',
	// '.gitmodules': '_file_git',
	// '.gitkeep': '_file_git',
	// '.mailmap': '_file_email',
	// CREDITS: '_file_credits',
	// 'credits.txt': '_file_credits',
	// 'credits.md': '_file_credits',
	// 'credits.md.rendered': '_file_credits',
	// '.flowconfig': '_file_flow',
	// 'git-history': '_file_git',
	// 'directive.ts': '_file_angular-directive',
	// 'directive.js': '_file_angular-directive',
	// 'favicon.ico': '_file_favicon',
};
