/* tslint:disable */
export const folderNames = {
	build: '_file_folder_dist',
	dist: '_file_folder_dist',
	out: '_file_folder_dist',
	src: '_file_folder_src',
	source: '_file_folder_src',
	assets: '_file_folder_assets',
	node_modules: '_file_folder_node',
	'.git': '_file_folder_github',
	'.github': '_file_folder_github',
	'.vscode': '_file_folder_vscode',
	test: '_file_folder_test',
	tests: '_file_folder_test',
	__test__: '_file_folder_test',
	__tests__: '_file_folder_test',
	js: '_file_folder_js',
	// added by @colin
	'.pnpm': '_file_folder_pnpm',
	drizzle: '_file_folder_drizzle',
	'.next': '_file_folder_next',
	'.bin': '_file_folder_bin',
	db: '_file_folder_db',
	database: '_file_folder_db',
	lib: '_file_folder_library',
	library: '_file_folder_library',
	public: '_file_folder_public',
	app: '_file_folder_app',
	'.svelte-kit': '_file_folder_svelte',
	'.sst': '_file_folder_sst',
};
