/* tslint:disable */
export const folderNamesExpanded = {
	build: '_file_folder_dist_open',
	dist: '_file_folder_dist_open',
	out: '_file_folder_dist_open',
	src: '_file_folder_src_open',
	source: '_file_folder_src_open',
	assets: '_file_folder_assets_open',
	node_modules: '_file_folder_node_open',
	'.git': '_file_folder_github_open',
	'.github': '_file_folder_github_open',
	'.vscode': '_file_folder_vscode_open',
	test: '_file_folder_test_open',
	tests: '_file_folder_test_open',
	__test__: '_file_folder_test_open',
	js: '_file_folder_js_open',
	// added by @colin
	'.pnpm': '_file_folder_pnpm_open',
	drizzle: '_file_folder_drizzle_open',
	'.next': '_file_folder_next_open',
	'.bin': '_file_folder_bin_open',
	db: '_file_folder_db_open',
	database: '_file_folder_db_open',
	lib: '_file_folder_library_open',
	library: '_file_folder_library_open',
	public: '_file_folder_public_open',
	app: '_file_folder_app_open',
	'.svelte-kit': '_file_folder_svelte_open',
	'.sst': '_file_folder_sst_open',
	'.wrangler': '_file_folder_wrangler_open',
	'.cargo': '_file_folder_cargo_open',
	'.bun': '_file_folder_bun_open',
	util: '_file_folder_util_open',
	utils: '_file_folder_util_open',
	packages: '_file_folder_packages_open',
	modules: '_file_folder_packages_open',
	routes: '_file_folder_routes_open',
	'.storybook': '_file_folder_storybook_open',
	stories: '_file_folder_storybook_open',
	'.wxt': '_file_folder_wxt_open',
};
